### ISSUE TITLE
Getting an undefined error occasionally

### ISSUE THREAD

**Issue by roshanpaiva** [IonicaBizau/node-ipinfo#13]
Any help on this is appreciated. This is what i see in my console. (running version 1.3.2)

``` 
[ 'TypeError: undefined is not a function',
     '    at /srv/www/<path>/current/node_modules/API-Common/node_modules/ipinfo/lib/index.js:51:32',
     '    at /srv/www/<path>/current/node_modules/API-Common/node_modules/ipinfo/node_modules/jsonrequest/lib/index.js:56:24',
     '    at opt_callback (/srv/www/<path>/current/node_modules/API-Common/node_modules/ipinfo/node_modules/jsonrequest/node_modules/tinyreq/lib/index.js:57:9)',```

**Comment by IonicaBizau** [comment]
This seems to be fixed.
